const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('app.js','utf8');
const nodes=new Map();
const context=vm.createContext({state:{connected:false,capabilities:new Set()},$:id=>{if(!nodes.has(id))nodes.set(id,{});return nodes.get(id)},hasCapability:cap=>context.state.capabilities.has(cap)});
const fn=source.match(/function updateBatteryCurrent\(current\)\{[\s\S]*?\n\}/)[0];
vm.runInContext(fn,context);
const render=value=>{context.updateBatteryCurrent(value);return nodes.get('#batteryCurrent').textContent};
assert.equal(render(1.24),'— A');
context.state.connected=true;
assert.equal(render(1.24),'— A');
context.state.capabilities.add('BATTERY_CURRENT');
assert.equal(render(1.24),'1.24 A');assert.equal(render(1.49),'1.49 A');assert.equal(render(0),'0.00 A');
assert.equal(render(NaN),'— A');assert.equal(render(Infinity),'— A');assert.equal(render(-1),'— A');
const route=source.split('\n').find(line=>line.includes('if(p[1]==="BATTERY_CURRENT")'));
vm.runInContext(`function route(p){${route}}`,context);
context.route(['@CFG','BATTERY_CURRENT','1.37']);assert.equal(nodes.get('#batteryCurrent').textContent,'1.37 A');
context.route(['@CFG','BATTERY_CURRENT']);assert.equal(nodes.get('#batteryCurrent').textContent,'— A');
context.state.connected=false;assert.equal(render(1.37),'— A');
console.log('Current telemetry precision, parsing, unavailable sensor and disconnect tests passed');

context.state.connected=true;
context.state.capabilities.add('CURRENT_ADC_DIAGNOSTICS');
context.state.currentAdc={raw:90,samples:100,ageMs:20,errors:0};
assert.equal(render(0.69),'0.69 A');
assert.match(nodes.get('#batteryCurrentStatus').title,/72\.5 mV.*100 samples/);
context.state.currentAdc.ageMs=2500;assert.equal(render(0.69),'— A');
context.state.currentAdc={raw:90,samples:0,ageMs:0,errors:0};assert.equal(render(0.69),'— A');
context.state.currentAdc={raw:130,samples:110,ageMs:10,errors:1};assert.equal(render(1),'1.00 A');
context.state.connected=false;assert.equal(render(1),'— A');assert.equal(context.state.currentAdc,null);

const html=fs.readFileSync('index.html','utf8');
assert.match(html.slice(0,html.indexOf('</header>')),/id="batteryCurrent"/);
assert.equal((html.match(/id="batteryCurrent"/g)||[]).length,1);
const diagStart=source.indexOf('  if(p[1]==="BATTERY_CURRENT_ADC"){');
const diagEnd=source.indexOf('\n  }',diagStart)+4;
vm.runInContext(`function diagnosticsRoute(p){${source.slice(diagStart,diagEnd)}}`,context);
context.state.connected=true;context.state.batteryCurrent=0.69;
context.diagnosticsRoute(['@CFG','BATTERY_CURRENT_ADC','90','123','25','0']);
assert.equal(context.state.currentAdc.samples,123);
assert.equal(nodes.get('#batteryCurrent').textContent,'0.69 A');
context.diagnosticsRoute(['@CFG','BATTERY_CURRENT_ADC','90','124','2501','1']);
assert.equal(nodes.get('#batteryCurrent').textContent,'— A');
context.diagnosticsRoute(['@CFG','BATTERY_CURRENT_ADC','90']);assert.equal(context.state.currentAdc.samples,124);
console.log('Current header location, ADC diagnostics parsing and stale reading detection passed');
