const assert=require("node:assert/strict");
const fs=require("node:fs");
const source=fs.readFileSync("app.js","utf8");
const html=fs.readFileSync("index.html","utf8");
assert.ok(!source.includes("SET_THROTTLE_RAMP"));
assert.ok(!source.includes("GET_THROTTLE_RAMP"));
assert.ok(!source.includes("throttleRampCommand"));
assert.ok(!html.includes("throttleRiseMs"));
assert.ok(!html.includes("Throttle rise limit"));
for(const file of ["app.js","index.html"])assert.equal(fs.readFileSync(file,"utf8"),fs.readFileSync("android/app/src/main/assets/configurator/"+file,"utf8"));
console.log("Fixed throttle rise configurator tests passed");
